acme_email: ENC[AES256_GCM,data:qoF+DWG7XVFLwOHHtLZRgZecePhbKuiw,iv:2WVKao2ab8XDxhmi9RTTqkiHMBWbZZY+Yhqll6h4+xY=,tag:r1UbpFp9A5zxURtA6xY7SA==,type:str]
dashboard_users: ENC[AES256_GCM,data:mmaeBA6MbZge0co6M0GFR8BISV7X5w==,iv:+QRMWQAx7wOzgvAR29iff8SEv2xN41Fx5S5RXiME6k4=,tag:3Z7t/FHG66zQrMxrylwSQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MXFCcWFUMlFUMGtVZzVV
            bkNaL2p0QmpyMzFmbW1Ja2J4YVFRUTg4RzFzClg3R0hYVWt5U3dxMFVPM2h1SWdN
            SzVqOEtJeUNZaUZHNU1DSU9jR09kRUkKLS0tIEd4Y0RlNTZlTGlMc3B1aUhKWmVk
            WXptN1c0YVBaL2N1NFcyblJWVitDdVEKB/c4hNsjYmlQApS9ITdlBGlms7fqt/06
            QZo+Isz7OWJbaALS7y5AH17igJ0gA4Ktpo1cbDkGocUj4dFxexhaCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wd4v5qfrkmtfm9nnhuqgh6mpd2mp6jj66e3jxs60qj7053lcjq6qyjcs0w
    lastmodified: "2026-08-04T18:22:43Z"
    mac: ENC[AES256_GCM,data:+WKxAV1AqOfLu1pVFgqdfc9qA1HwiulBrRKdcoFgNm9yxs4eQTwVPUE6voqZ81qVpZNvrV3bWeqTjjT+W8NR98YXYYUfLjP12OSPjN2ev2rBYjfP2XV6s6hjjQfPhznxjQBkoPgg1SrKW+TbWBmJqjO592R0GN7T2cwxyF0jHbY=,iv:Ky6wmVc/JN/3qHctzjMvYGwc/igHWmrLZ0m32rzYQ+I=,tag:LUb1gBdT3UmQv9//kwnLeQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
